### ISSUE TITLE
Dropdown on IOS not focus

### ISSUE THREAD

**Issue by bastaware** [alexplumb/material-ui-phone-number#11]
There are some issues when using the dropdown on IOS. It seems the problem is that the dropdown is positioned before the soft-keyboard is removed and therefore centered outside the screen. Also sometimes dragevents are sent to the page below.

![problem2](https://user-images.githubusercontent.com/1000036/56856947-84606000-6966-11e9-9e8c-6727527bba1a.gif)

**Comment by alexplumb** [comment]
Hi @bastaware thanks for reporting this issue! Version 2.0 includes support for a new `native` property that you should be able to use to make it work much better on mobile devices. This release is currently in beta since it depends on the upcoming material-ui v4 update, but you can test it if you'd like by installing `material-ui-phone-number@next`
